# Generated by Django 2.0.13 on 2019-10-26 05:13

import digitals.catalogue.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=digitals.catalogue.models.CustomFileField(upload_to='files/%Y/%m/%d'),
        ),
    ]
